# Generated by Django 5.1.3 on 2024-11-06 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Git',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Гит',
                'verbose_name_plural': 'Гит',
            },
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=150, verbose_name='sha')),
                ('url', models.URLField(verbose_name='URL')),
                ('author', models.EmailField(max_length=254, verbose_name='Емайл автора')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('git', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.git', verbose_name='Гит')),
            ],
            options={
                'verbose_name': 'Коммит',
                'verbose_name_plural': 'Коммиты',
            },
        ),
    ]
