# Generated by Django 5.1.3 on 2024-11-11 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_git_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='author',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Емайл автора'),
        ),
        migrations.AlterField(
            model_name='git',
            name='name',
            field=models.CharField(help_text='формат: имя_владельца/название', max_length=255, verbose_name='Название репозитория'),
        ),
    ]
